name: hexlet-cov

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
      - name: install1
        run:  pip install poetry
      - name: install2
        run: make install
      # - name: run-test-cov
      #   run:  make test-cov
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 5bf385ad77f103b356d2d919d527c21d79f51b063242a754f37fa0b5b913efe4
        with:
          coverageCommand: make test-cov
          debug: true